# Generated by Django 4.1.2 on 2022-11-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todo_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
